#!/usr/bin/env python3
"""Generate the production .env for all six services in one pass.

Each service loads ONLY its own .env (configs/__init__.py), so a production
deploy needs six files that agree with each other on three values:

    JWT_SECRET_KEY, SESSION_SECRET, JWT_ISSUER

LoginServices signs the tokens and the other five verify them. If any one of
those three differs by a single byte, every authenticated request 401s and the
symptom (a login that "works" but every page fails) points nowhere near the
cause. Generating all six from one source removes that failure mode.

Usage
-----
Dry run first -- prints what it would write, touches nothing:

    python make_prod_env.py --db-host db.internal --db-user hotelerp \\
        --db-password 'REDACTED' --cors https://erp.example.com --dry-run

Write for real (refuses to clobber an existing .env unless --force):

    python make_prod_env.py --db-host db.internal --db-user hotelerp \\
        --db-password 'REDACTED' --cors https://erp.example.com

Stage the files somewhere else instead of writing into the service dirs:

    python make_prod_env.py ... --out-dir /tmp/envs

Notes
-----
* Secrets are generated here with `secrets.token_urlsafe(64)`. They are never
  printed in full and never committed -- .env is gitignored, and this repo is
  public.
* Only the gateway binds publicly. The other five stay on 127.0.0.1 so they are
  unreachable except through LoginServices.
* Pass --db-password '-' to be prompted instead of putting it in shell history.
"""

from __future__ import annotations

import argparse
import getpass
import secrets
import sys
from pathlib import Path
from urllib.parse import quote

# service -> (bind host, port, database, wants cross-service URLs, is gateway)
SERVICES = {
    "LoginServices":      ("0.0.0.0",   8000, "hotelerp_users",      True,  True),
    "UserServices":       ("127.0.0.1", 8020, "hotelerp_users",      False, False),
    "MasterDataServices": ("127.0.0.1", 8030, "hotelerp_masterdata", False, False),
    "HotelServices":      ("127.0.0.1", 8040, "hotelerp_hotel",      False, False),
    "RestaurantServices": ("127.0.0.1", 8050, "hotelerp_restaurant", True,  False),
    "BarServices":        ("127.0.0.1", 8060, "hotelerp_bar",        True,  False),
}

INTERNAL_URLS = [
    ("USER_SERVICE_URL",       8020),
    ("MASTER_SERVICE_URL",     8030),
    ("HOTEL_SERVICE_URL",      8040),
    ("RESTAURANT_SERVICE_URL", 8050),
    ("BAR_SERVICE_URL",        8060),
]


def build(service: str, cfg: tuple, shared: dict, args) -> str:
    host, port, db, wants_urls, is_gateway = cfg
    # Credentials are percent-encoded: a '@' or '/' in a password otherwise
    # truncates the DSN and the service connects somewhere unintended.
    user = quote(args.db_user, safe="")
    pw = quote(shared["db_password"], safe="")
    dsn = f"mysql+pymysql://{user}:{pw}@{args.db_host}:{args.db_port}/{db}"

    L = [
        "# ============================================================",
        f"# {service} - PRODUCTION",
        f"# Generated by make_prod_env.py. Do not commit this file.",
        "# ============================================================",
        "",
        "ASCEND_ENV=production",
        "",
        f"SERVICE_HOST={host}",
        f"SERVICE_PORT={port}",
        "",
        "# Identical in all six services - do not edit one in isolation.",
        f"JWT_SECRET_KEY={shared['jwt']}",
        f"SESSION_SECRET={shared['session']}",
        f"JWT_ISSUER={args.jwt_issuer}",
        f"ACCESS_TOKEN_EXPIRE_MINUTES={args.access_ttl}",
        f"REFRESH_TOKEN_EXPIRE_MINUTES={args.refresh_ttl}",
        "",
        f"DB_URI={dsn}",
        f"DB_POOL_SIZE={args.pool_size}",
        f"DB_MAX_OVERFLOW={args.max_overflow}",
        "DB_POOL_TIMEOUT=30",
        "DB_POOL_RECYCLE=1800",
        "",
        "# Exact origins the SPA is served from. Wildcard is rejected by config.",
        f"CORS_ALLOWED_ORIGINS={args.cors}",
    ]

    if wants_urls:
        L += ["", "# Cross-service calls stay on loopback - never public."]
        L += [f"{name}=http://127.0.0.1:{p}" for name, p in INTERNAL_URLS]

    if is_gateway:
        L += [
            "",
            "# Gateway only",
            f"LOGIN_RATE_LIMIT_PER_MINUTE={args.rate_limit}",
            f"LOGIN_RATE_LIMIT_BURST={args.rate_burst}",
            "PROXY_TIMEOUT_SECONDS=30",
            "UPSTREAM_TIMEOUT_SECONDS=10",
        ]

    L += ["", f"UPLOAD_MAX_BYTES={args.upload_max}", ""]
    return "\n".join(L)


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate production .env files for all six services.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--db-host", required=True, help="Production MySQL host")
    p.add_argument("--db-port", default="3306")
    p.add_argument("--db-user", required=True)
    p.add_argument("--db-password", required=True,
                   help="Use '-' to be prompted instead of using shell history")
    p.add_argument("--cors", required=True,
                   help="Comma-separated live origins, e.g. https://erp.example.com")
    p.add_argument("--jwt-issuer", default="hotelerp-login")
    p.add_argument("--access-ttl", default="60")
    p.add_argument("--refresh-ttl", default="1440")
    p.add_argument("--pool-size", default="10")
    p.add_argument("--max-overflow", default="20")
    p.add_argument("--rate-limit", default="10")
    p.add_argument("--rate-burst", default="3")
    p.add_argument("--upload-max", default="5242880")
    p.add_argument("--out-dir", default=None,
                   help="Stage files here instead of writing into service dirs")
    p.add_argument("--force", action="store_true", help="Overwrite existing .env")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    if "*" in args.cors:
        print("ERROR: wildcard CORS is rejected by the config layer. "
              "List the exact origins.", file=sys.stderr)
        return 2
    if not any(o.strip().startswith("https://") for o in args.cors.split(",")):
        print("WARNING: no https:// origin in --cors. Session cookies are set "
              "https-only in production, so a plain-http origin will not hold "
              "a session.", file=sys.stderr)

    pw = getpass.getpass("Production DB password: ") if args.db_password == "-" else args.db_password
    if not pw:
        print("ERROR: empty DB password.", file=sys.stderr)
        return 2

    # One pair of secrets, shared by all six. This is the whole point.
    shared = {
        "jwt": secrets.token_urlsafe(64),
        "session": secrets.token_urlsafe(64),
        "db_password": pw,
    }

    base = Path(__file__).resolve().parent
    out_base = Path(args.out_dir).resolve() if args.out_dir else None
    if out_base:
        out_base.mkdir(parents=True, exist_ok=True)

    planned, skipped = [], []
    for svc, cfg in SERVICES.items():
        target = (out_base / f"{svc}.env") if out_base else (base / svc / ".env")
        if target.exists() and not args.force and not args.dry_run:
            skipped.append(target)
            continue
        planned.append((svc, target, build(svc, cfg, shared, args)))

    if skipped:
        print("REFUSING to overwrite (pass --force if that is intended):",
              file=sys.stderr)
        for s in skipped:
            print(f"  {s}", file=sys.stderr)
        if not planned:
            return 1

    for svc, target, body in planned:
        if args.dry_run:
            print(f"--- would write {target} ({len(body.splitlines())} lines) ---")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding="utf-8")
            try:
                target.chmod(0o600)  # no-op on Windows, correct on the server
            except OSError:
                pass
            print(f"wrote {target}")

    print()
    print(f"{'DRY RUN - nothing written' if args.dry_run else 'Done'}: "
          f"{len(planned)} service(s)")
    print(f"  ASCEND_ENV  production")
    print(f"  DB          {args.db_host}:{args.db_port} as {args.db_user}")
    print(f"  CORS        {args.cors}")
    print(f"  JWT secret  {shared['jwt'][:6]}...{shared['jwt'][-4:]} "
          f"({len(shared['jwt'])} chars, identical in all six)")
    if not args.dry_run:
        print()
        print("Next: verify each service starts, then confirm the six agree:")
        print("  python make_prod_env.py --verify-only  (see verify_prod_env.py)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
