"""night audit business date and audit log

Adds the two tables the Night Audit module needs, and nothing else.

    hotel_business_date   the property's operating date (one row per company)
    night_audit           one immutable record per audited business date

WHAT WAS DELIBERATELY REMOVED FROM THE AUTOGENERATED VERSION
    `alembic revision --autogenerate` also emitted ~15
    `alter_column(..., server_default=now())` statements and a `drop_index` on
    housekeeper_task.schedule_date. None of those belong to this change -- they
    are pre-existing drift between the hand-built schema and the ORM models,
    present since the baseline. Applying them here would rewrite columns on the
    live reservation and payment tables as a side effect of adding a feature,
    so they are left for whoever audits that drift on purpose.

Revision ID: b7c2fe891ac3
Revises: 94a2a9d04fc0
Create Date: 2026-08-27 04:25:21.601346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7c2fe891ac3'
down_revision: Union[str, None] = '94a2a9d04fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'hotel_business_date',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('business_date', sa.Date(), nullable=False),
        sa.Column('last_audit_at', sa.DateTime(), nullable=True),
        sa.Column('last_audit_by', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(length=100), nullable=True),
        sa.Column('company_id', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        # One operating date per property. Makes a concurrent first-time
        # initialisation fail rather than create two divergent dates.
        sa.UniqueConstraint('company_id', name='uq_business_date_company'),
    )
    op.create_index(op.f('ix_hotel_business_date_business_date'), 'hotel_business_date', ['business_date'], unique=False)
    op.create_index(op.f('ix_hotel_business_date_company_id'), 'hotel_business_date', ['company_id'], unique=False)
    op.create_index(op.f('ix_hotel_business_date_id'), 'hotel_business_date', ['id'], unique=False)
    op.create_index(op.f('ix_hotel_business_date_status'), 'hotel_business_date', ['status'], unique=False)

    op.create_table(
        'night_audit',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('night_audit_id', sa.String(length=100), nullable=False),
        sa.Column('business_date', sa.Date(), nullable=False),
        sa.Column('next_business_date', sa.Date(), nullable=True),
        sa.Column('audit_status', sa.String(length=20), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('run_by', sa.String(length=100), nullable=True),
        sa.Column('error_message', sa.String(length=500), nullable=True),
        sa.Column('rooms_total', sa.Integer(), nullable=True),
        sa.Column('rooms_occupied', sa.Integer(), nullable=True),
        sa.Column('occupancy_percent', sa.Float(), nullable=True),
        sa.Column('room_nights', sa.Integer(), nullable=True),
        sa.Column('arrivals_expected', sa.Integer(), nullable=True),
        sa.Column('arrivals_completed', sa.Integer(), nullable=True),
        sa.Column('departures_expected', sa.Integer(), nullable=True),
        sa.Column('departures_completed', sa.Integer(), nullable=True),
        sa.Column('in_house', sa.Integer(), nullable=True),
        sa.Column('stayovers', sa.Integer(), nullable=True),
        sa.Column('no_shows_marked', sa.Integer(), nullable=True),
        sa.Column('no_show_reservation_ids', sa.JSON(), nullable=True),
        sa.Column('room_revenue', sa.Float(), nullable=True),
        sa.Column('extra_charges', sa.Float(), nullable=True),
        sa.Column('tax_amount', sa.Float(), nullable=True),
        sa.Column('discount_amount', sa.Float(), nullable=True),
        sa.Column('gross_revenue', sa.Float(), nullable=True),
        sa.Column('payments_collected', sa.Float(), nullable=True),
        sa.Column('payment_breakdown', sa.JSON(), nullable=True),
        sa.Column('outstanding_balance', sa.Float(), nullable=True),
        sa.Column('token', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(length=100), nullable=True),
        sa.Column('company_id', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        # THE idempotency guarantee. A double-clicked button, a retried
        # request, a second browser tab and a second operator all collide
        # here rather than recording the same night twice.
        sa.UniqueConstraint('company_id', 'business_date', name='uq_night_audit_company_date'),
    )
    op.create_index(op.f('ix_night_audit_audit_status'), 'night_audit', ['audit_status'], unique=False)
    op.create_index(op.f('ix_night_audit_business_date'), 'night_audit', ['business_date'], unique=False)
    op.create_index(op.f('ix_night_audit_company_id'), 'night_audit', ['company_id'], unique=False)
    op.create_index(op.f('ix_night_audit_id'), 'night_audit', ['id'], unique=False)
    op.create_index(op.f('ix_night_audit_night_audit_id'), 'night_audit', ['night_audit_id'], unique=True)
    op.create_index(op.f('ix_night_audit_status'), 'night_audit', ['status'], unique=False)
    op.create_index(op.f('ix_night_audit_token'), 'night_audit', ['token'], unique=True)


def downgrade() -> None:
    op.drop_index(op.f('ix_night_audit_token'), table_name='night_audit')
    op.drop_index(op.f('ix_night_audit_status'), table_name='night_audit')
    op.drop_index(op.f('ix_night_audit_night_audit_id'), table_name='night_audit')
    op.drop_index(op.f('ix_night_audit_id'), table_name='night_audit')
    op.drop_index(op.f('ix_night_audit_company_id'), table_name='night_audit')
    op.drop_index(op.f('ix_night_audit_business_date'), table_name='night_audit')
    op.drop_index(op.f('ix_night_audit_audit_status'), table_name='night_audit')
    op.drop_table('night_audit')
    op.drop_index(op.f('ix_hotel_business_date_status'), table_name='hotel_business_date')
    op.drop_index(op.f('ix_hotel_business_date_id'), table_name='hotel_business_date')
    op.drop_index(op.f('ix_hotel_business_date_company_id'), table_name='hotel_business_date')
    op.drop_index(op.f('ix_hotel_business_date_business_date'), table_name='hotel_business_date')
    op.drop_table('hotel_business_date')
