"""reservation cancellation reason

Adds three nullable columns to `room_reservation`, and nothing else:

    cancellation_reason   why the booking was cancelled (free text)
    cancelled_at          when the cancellation was recorded
    cancelled_by          the user who recorded it

WHY NULLABLE, AND WHY NOTHING IS BACK-FILLED
    Every reservation already in the client's database predates these columns.
    Some of them are cancelled, and nobody wrote down why -- so there is no
    honest value to back-fill. Inventing one ("Cancelled", "Migrated") would
    put a fact in the audit trail that nobody ever asserted. They stay NULL,
    and the UI reads a missing reason as "not recorded" rather than as blank.

WHY THIS IS HAND-WRITTEN AND NOT AUTOGENERATED
    `alembic revision --autogenerate` against this database also emits ~15
    `alter_column(..., server_default=now())` statements and a `drop_index` on
    housekeeper_task.schedule_date. That is pre-existing drift between the
    hand-built schema and the ORM models, documented in the previous revision
    and deliberately left alone there for the same reason it is left alone
    here: applying it would rewrite columns on the live reservation and payment
    tables as a side effect of adding a feature.

    So this revision was written by hand and contains only the three ADD
    COLUMNs. Adding a nullable column is metadata-only on MySQL 8 (ALGORITHM=
    INSTANT), so it does not rewrite the table or lock out the front desk.

Revision ID: c4f1a7e93b52
Revises: b7c2fe891ac3
Create Date: 2026-08-31 17:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4f1a7e93b52'
down_revision: Union[str, None] = 'b7c2fe891ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'room_reservation',
        sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    )
    op.add_column(
        'room_reservation',
        sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    )
    op.add_column(
        'room_reservation',
        sa.Column('cancelled_by', sa.String(length=100), nullable=True),
    )


def downgrade() -> None:
    # Dropping these loses the recorded reasons permanently -- there is nowhere
    # else they are kept. That is the correct behaviour for a downgrade of this
    # revision, but it is worth knowing before running one.
    op.drop_column('room_reservation', 'cancelled_by')
    op.drop_column('room_reservation', 'cancelled_at')
    op.drop_column('room_reservation', 'cancellation_reason')
