"""align bill payment status index name

Revision ID: 87d058e6824d
Revises: g7a8b9c0d1e2
Create Date: 2026-10-06 19:48:18.756574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87d058e6824d'
down_revision: Union[str, None] = 'g7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurant_bill_payment_status', table_name='restaurant_bill_payment')
    op.create_index('ix_restaurant_bill_payment_lifecycle_status', 'restaurant_bill_payment', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurant_bill_payment_lifecycle_status', table_name='restaurant_bill_payment')
    op.create_index('ix_restaurant_bill_payment_status', 'restaurant_bill_payment', ['status'], unique=False)
    # ### end Alembic commands ###
