"""align bill payment status index name

Revision ID: 16334f06ab61
Revises: j3c4d5e6f7a8
Create Date: 2026-10-06 19:48:18.648886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '16334f06ab61'
down_revision: Union[str, None] = 'j3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bar_bill_payment_status', table_name='bar_bill_payment')
    op.create_index('ix_bar_bill_payment_lifecycle_status', 'bar_bill_payment', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bar_bill_payment_lifecycle_status', table_name='bar_bill_payment')
    op.create_index('ix_bar_bill_payment_status', 'bar_bill_payment', ['status'], unique=False)
    # ### end Alembic commands ###
