#!/usr/bin/env python3
"""Run Alembic against one -- or every -- HotelERP database.

There are five databases and six services; LoginServices and UserServices both
read hotelerp_users, and LoginServices' model set (`users` only) is a subset of
UserServices'. So migrations are keyed by DATABASE, and each database has one
owning service whose models are the source of truth for it.

Because every service defines a top-level `configs` module, the six cannot share
a process. Each database is therefore migrated in its own subprocess with cwd
set to the owning service directory -- the same pattern as
Backend/tests/run_all.py.

    # what would change, without touching anything
    python Backend/migrations/migrate.py check

    # stamp the existing hand-built schema as the baseline (once, per database)
    python Backend/migrations/migrate.py stamp all head

    # create a revision from the model diff for one database
    python Backend/migrations/migrate.py revision users -m "add guest email"

    # apply
    python Backend/migrations/migrate.py upgrade users
    python Backend/migrations/migrate.py upgrade all

    # where each database currently sits
    python Backend/migrations/migrate.py current all
    python Backend/migrations/migrate.py history hotel
    python Backend/migrations/migrate.py downgrade bar -1
"""
from __future__ import annotations

import argparse
import os
import pathlib
import subprocess
import sys

# database key -> owning service (whose models define that schema)
DATABASES = {
    "users": "UserServices",
    "masterdata": "MasterDataServices",
    "hotel": "HotelServices",
    "restaurant": "RestaurantServices",
    "bar": "BarServices",
}

ROOT = pathlib.Path(__file__).resolve().parents[2]
MIGRATIONS = ROOT / "Backend" / "migrations"
SERVICES = ROOT / "Backend" / "Services"


# --------------------------------------------------------------------------
# worker: runs inside the owning service's directory, one database only
# --------------------------------------------------------------------------
def _worker(db: str, command: str, rest: list[str]) -> int:
    from alembic import command as alembic_command
    from alembic.config import Config
    from alembic.util.exc import CommandError

    service = DATABASES[db]
    versions = MIGRATIONS / "versions" / db
    versions.mkdir(parents=True, exist_ok=True)

    cfg = Config(str(MIGRATIONS / "alembic.ini"))
    cfg.set_main_option("script_location", str(MIGRATIONS))
    # Each database keeps its own linear history in its own directory, so a
    # revision for `bar` can never end up in `hotel`'s chain.
    cfg.set_main_option("version_locations", str(versions))
    cfg.cmd_opts = argparse.Namespace(x=[f"service={service}"])

    try:
        if command == "revision":
            parser = argparse.ArgumentParser(prog="revision")
            parser.add_argument("-m", "--message", required=True)
            # An existing hand-built schema must be baselined with an EMPTY
            # revision, not an autogenerated one. Autogenerate diffs the models
            # against the live database, and on this project that diff is 147
            # operations -- including unique constraints the data may not
            # satisfy. Baseline empty, stamp, then let later revisions carry
            # real changes.
            parser.add_argument("--empty", action="store_true",
                                help="baseline marker: no schema operations")
            ns = parser.parse_args(rest)
            alembic_command.revision(cfg, message=ns.message,
                                     autogenerate=not ns.empty)
        elif command == "check":
            alembic_command.check(cfg)
        elif command == "upgrade":
            alembic_command.upgrade(cfg, rest[0] if rest else "head")
        elif command == "downgrade":
            if not rest:
                raise SystemExit("downgrade needs a target, e.g. -1")
            alembic_command.downgrade(cfg, rest[0])
        elif command == "stamp":
            alembic_command.stamp(cfg, rest[0] if rest else "head")
        elif command == "current":
            alembic_command.current(cfg, verbose=True)
        elif command == "history":
            alembic_command.history(cfg, verbose=True)
        elif command == "heads":
            alembic_command.heads(cfg, verbose=True)
        else:
            raise SystemExit(f"unsupported command {command!r}")
    except CommandError as exc:
        print(f"alembic: {exc}", file=sys.stderr)
        return 1
    return 0


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------
def run(db: str, command: str, rest: list[str]) -> int:
    service = DATABASES[db]
    cwd = SERVICES / service
    if not (cwd / ".env").exists():
        print(f"  no {service}/.env -- skipping", file=sys.stderr)
        return 1

    proc = subprocess.run(
        [sys.executable, str(pathlib.Path(__file__).resolve()),
         "--worker", db, command, *rest],
        cwd=cwd,
        env={**os.environ, "DB_AUTO_CREATE": "false"},
    )
    return proc.returncode


def targets(name: str) -> list[str]:
    if name in ("all", "*"):
        return list(DATABASES)
    if name not in DATABASES:
        raise SystemExit(
            f"unknown database {name!r}. Known: {', '.join(DATABASES)}, or 'all'."
        )
    return [name]


def main() -> int:
    argv = sys.argv[1:]
    if argv and argv[0] == "--worker":
        return _worker(argv[1], argv[2], argv[3:])

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("command", help="check, revision, upgrade, downgrade, stamp, current, history, heads")
    parser.add_argument(
        "database",
        nargs="?",
        default="all",
        help=f"one of {', '.join(DATABASES)} -- or 'all' (default)",
    )
    parser.add_argument("rest", nargs=argparse.REMAINDER, help="passed to alembic")
    args = parser.parse_args()

    if (args.command == "revision" and args.database == "all"
            and "--empty" not in args.rest):
        raise SystemExit(
            "refusing to autogenerate a revision for every database at once -- "
            'name one, e.g. `revision users -m "add guest email"`. '
            "(`revision all --empty -m ...` is allowed: an empty baseline "
            "carries no schema operations, so there is nothing to get wrong.)"
        )

    failures = []
    for db in targets(args.database):
        print(f"== {db}  ({DATABASES[db]}) ==")
        if run(db, args.command, args.rest) != 0:
            failures.append(db)
        print()

    if failures:
        print(f"failed: {', '.join(failures)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
