"""widen roles.updated_by and add lookup indexes

Revision ID: 8a16d8b06aaf
Revises: b2c4e6f8a91d
Create Date: 2026-10-06 19:47:59.342291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '8a16d8b06aaf'
down_revision: Union[str, None] = 'b2c4e6f8a91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'updated_by',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=False)
    op.create_index(op.f('ix_roles_updated_by'), 'roles', ['updated_by'], unique=False)
    op.create_index(op.f('ix_submenus_submenu_name'), 'submenus', ['submenu_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submenus_submenu_name'), table_name='submenus')
    op.drop_index(op.f('ix_roles_updated_by'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.alter_column('roles', 'updated_by',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    # ### end Alembic commands ###
